# Building workflow for ubuntu 20.04 or later.
#
# 1. Use this docker file to build the executable.
#    docker build -t scr_ubuntu -f Dockerfile_Ubuntu ./
#
# 2. Run the built image.
#    docker run scr_ubuntu
#
# 3. Check the created container id.
#    docker ps -a
#
# 4. Use "docker cp" to get the built executable.
#    docker cp <CONTAINER ID>:/Simple-Command-Runner/build/Release/SimpleCommandRunner ./

# Base image
FROM ubuntu:20.04

# Install packages
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
            ca-certificates build-essential libgtk-3-dev git python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install meson
RUN pip3 install meson ninja

# Clone the repo
WORKDIR /
RUN git clone -b libui --depth 1 https://github.com/matyalatte/Simple-Command-Runner.git

# Build
WORKDIR /Simple-Command-Runner/shell_scripts
RUN bash build.sh
