@echo off
REM Builds wxWidgets with CMake and Visual Studio 2022.
REM The library will be installed in C:\wxWidgets-%WX_VERSION%\%BUILD_TYPE%\Installed

REM Edit here if you won't use Visual Studio 2022.
set GENERATOR=Visual Studio 17 2022
echo Generator: %GENERATOR%

set COMPILER_FLAGS=-D CMAKE_CXX_FLAGS="/DWIN32 /D_WINDOWS"^
 -D CMAKE_CXX_FLAGS_DEBUG="/MDd /Zi /Ob0 /Od /RTC1 /GR /EHsc"^
 -D CMAKE_CXX_FLAGS_RELEASE="/MT /O1 /DNDEBUG /GL /GR- /D_HAS_EXCEPTIONS=0"^
 -D CMAKE_STATIC_LINKER_FLAGS_RELEASE="/LTCG"
echo COMPILER_FLAGS: %COMPILER_FLAGS%

REM You can specify build type as an argument like "build_wxWidgets.bat Release"
if /I "%~1"=="Debug" (
    set BUILD_TYPE=Debug
) else (
    set BUILD_TYPE=Release
)
echo Build type: %BUILD_TYPE%

REM wxWidgets version is defined in ./Simple-Command-Runner/WX_VERSION.txt
set /p WX_VERSION=< %~dp0\..\WX_VERSION.txt
set INSTALL_DIR=%USERPROFILE%/wxWidgets-%WX_VERSION%/%BUILD_TYPE%/Installed
echo Install dir: %INSTALL_DIR%

set CMAKE_OPTIONS=-G "%GENERATOR%"^
 -A x64^
 -D CMAKE_CONFIGURATION_TYPES=%BUILD_TYPE%^
 -D CMAKE_INSTALL_PREFIX=%INSTALL_DIR%

REM wx* options are defined in wxWidgets/build/cmake/options.cmake
set LIB_OPTIONS=-D wxUSE_REGEX=OFF^
 -D wxUSE_ZLIB=OFF^
 -D wxUSE_EXPAT=OFF^
 -D wxUSE_LIBJPEG=OFF^
 -D wxUSE_LIBPNG=OFF^
 -D wxUSE_LIBTIFF=OFF^
 -D wxUSE_NANOSVG=OFF^
 -D wxUSE_LIBLZMA=OFF^
 -D wxUSE_OPENGL=OFF

set NON_GUI_OPTIONS=-D wxUSE_INTL=OFF^
 -D wxUSE_XLOCALE=OFF^
 -D wxUSE_CONFIG=OFF^
 -D wxUSE_SOCKETS=OFF^
 -D wxUSE_IPV6=OFF^
 -D wxUSE_IPC=OFF^
 -D wxUSE_CONSOLE_EVENTLOOP=OFF^
 -D wxUSE_ANY=OFF^
 -D wxUSE_APPLE_IEEE=OFF^
 -D wxUSE_ARCHIVE_STREAMS=OFF^
 -D wxUSE_BASE64=OFF^
 -D wxUSE_STACKWALKER=OFF^
 -D wxUSE_ON_FATAL_EXCEPTION=OFF^
 -D wxUSE_EXCEPTIONS=OFF^
 -D wxUSE_DATETIME=OFF^
 -D wxUSE_CMDLINE_PARSER=OFF^
 -D wxUSE_DIALUP_MANAGER=OFF^
 -D wxUSE_DYNAMIC_LOADER=OFF^
 -D wxUSE_FFILE=OFF^
 -D wxUSE_FILE_HISTORY=OFF^
 -D wxUSE_FILESYSTEM=OFF^
 -D wxUSE_FONTENUM=OFF^
 -D wxUSE_FONTMAP=OFF^
 -D wxUSE_FS_ARCHIVE=OFF^
 -D wxUSE_FS_INET=OFF^
 -D wxUSE_FS_ZIP=OFF^
 -D wxUSE_FSVOLUME=OFF^
 -D wxUSE_FSWATCHER=OFF^
 -D wxUSE_GEOMETRY=OFF^
 -D wxUSE_MIMETYPE=OFF^
 -D wxUSE_PRINTF_POS_PARAMS=OFF^
 -D wxUSE_SECRETSTORE=OFF^
 -D wxUSE_SNGLINST_CHECKER=OFF^
 -D wxUSE_SOUND=OFF^
 -D wxUSE_SPELLCHECK=OFF^
 -D wxUSE_STDPATHS=OFF^
 -D wxUSE_STOPWATCH=OFF^
 -D wxUSE_SYSTEM_OPTIONS=OFF^
 -D wxUSE_TARSTREAM=OFF^
 -D wxUSE_TEXTBUFFER=OFF^
 -D wxUSE_TEXTFILE=OFF^
 -D wxUSE_TIMER=OFF^
 -D wxUSE_WEBREQUEST=OFF^
 -D wxUSE_ZIPSTREAM=OFF^
 -D wxUSE_VARIANT=OFF^
 -D wxUSE_URL=OFF^
 -D wxUSE_PROTOCOL=OFF^
 -D wxUSE_PROTOCOL_FTP=OFF^
 -D wxUSE_PROTOCOL_HTTP=OFF^
 -D wxUSE_PROTOCOL_FILE=OFF^
 -D wxUSE_THREADS=OFF^
 -D wxUSE_DBGHELP=OFF^
 -D wxUSE_INICONF=OFF

set BIG_GUI_OPTIONS=-D wxUSE_DOC_VIEW_ARCHITECTURE=OFF^
 -D wxUSE_HELP=OFF^
 -D wxUSE_MS_HTML_HELP=OFF^
 -D wxUSE_HTML=OFF^
 -D wxUSE_WXHTML_HELP=OFF^
 -D wxUSE_XRC=OFF^
 -D wxUSE_XML=OFF^
 -D wxUSE_AUI=OFF^
 -D wxUSE_PROPGRID=OFF^
 -D wxUSE_RIBBON=OFF^
 -D wxUSE_STC=OFF^
 -D wxUSE_CONSTRAINTS=OFF^
 -D wxUSE_LOGGUI=OFF^
 -D wxUSE_LOGWINDOW=OFF^
 -D wxUSE_LOG_DIALOG=OFF^
 -D wxUSE_MDI=OFF^
 -D wxUSE_MDI_ARCHITECTURE=OFF^
 -D wxUSE_MEDIACTRL=OFF^
 -D wxUSE_RICHTEXT=OFF^
 -D wxUSE_POSTSCRIPT=OFF^
 -D wxUSE_AFM_FOR_POSTSCRIPT=OFF^
 -D wxUSE_PRINTING_ARCHITECTURE=OFF^
 -D wxUSE_SVG=OFF^
 -D wxUSE_WEBVIEW=OFF^
 -D wxUSE_GRAPHICS_CONTEXT=OFF^
 -D wxUSE_GRAPHICS_DIRECT2D=OFF^
 -D wxUSE_CLIPBOARD=OFF

set CTRL_OPTIONS=-D wxUSE_MARKUP=OFF^
 -D wxUSE_ACCEL=OFF^
 -D wxUSE_ACTIVITYINDICATOR=OFF^
 -D wxUSE_ADDREMOVECTRL=OFF^
 -D wxUSE_ANIMATIONCTRL=OFF^
 -D wxUSE_BANNERWINDOW=OFF^
 -D wxUSE_ARTPROVIDER_STD=OFF^
 -D wxUSE_ARTPROVIDER_TANGO=OFF^
 -D wxUSE_BMPBUTTON=OFF^
 -D wxUSE_BITMAPCOMBOBOX=OFF^
 -D wxUSE_CALENDARCTRL=OFF^
 -D wxUSE_CARET=OFF^
 -D wxUSE_CHECKLISTBOX=OFF^
 -D wxUSE_CHOICEBOOK=OFF^
 -D wxUSE_COLLPANE=OFF^
 -D wxUSE_COLOURPICKERCTRL=OFF^
 -D wxUSE_COMBOBOX=OFF^
 -D wxUSE_COMBOCTRL=OFF^
 -D wxUSE_COMMANDLINKBUTTON=OFF^
 -D wxUSE_DATAVIEWCTRL=OFF^
 -D wxUSE_NATIVE_DATAVIEWCTRL=OFF^
 -D wxUSE_DATEPICKCTRL=OFF^
 -D wxUSE_DISPLAY=OFF^
 -D wxUSE_EDITABLELISTBOX=OFF^
 -D wxUSE_FILECTRL=OFF^
 -D wxUSE_FONTPICKERCTRL=OFF^
 -D wxUSE_GAUGE=OFF^
 -D wxUSE_GRID=OFF^
 -D wxUSE_HEADERCTRL=OFF^
 -D wxUSE_HYPERLINKCTRL=OFF^
 -D wxUSE_IMAGLIST=OFF^
 -D wxUSE_INFOBAR=OFF^
 -D wxUSE_LISTBOOK=OFF^
 -D wxUSE_LISTBOX=OFF^
 -D wxUSE_LISTCTRL=OFF^
 -D wxUSE_NOTEBOOK=OFF^
 -D wxUSE_NOTIFICATION_MESSAGE=OFF^
 -D wxUSE_ODCOMBOBOX=OFF^
 -D wxUSE_PREFERENCES_EDITOR=OFF^
 -D wxUSE_RADIOBOX=OFF^
 -D wxUSE_RADIOBTN=OFF^
 -D wxUSE_RICHMSGDLG=OFF^
 -D wxUSE_RICHTOOLTIP=OFF^
 -D wxUSE_REARRANGECTRL=OFF^
 -D wxUSE_SASH=OFF^
 -D wxUSE_SCROLLBAR=OFF^
 -D wxUSE_SEARCHCTRL=OFF^
 -D wxUSE_SLIDER=OFF^
 -D wxUSE_SPLITTER=OFF^
 -D wxUSE_STATBMP=OFF^
 -D wxUSE_STATBOX=OFF^
 -D wxUSE_STATUSBAR=OFF^
 -D wxUSE_TASKBARBUTTON=OFF^
 -D wxUSE_TASKBARICON=OFF^
 -D wxUSE_TOOLBAR_NATIVE=OFF^
 -D wxUSE_TIMEPICKCTRL=OFF^
 -D wxUSE_TOGGLEBTN=OFF^
 -D wxUSE_TOOLBAR=OFF^
 -D wxUSE_TOOLBOOK=OFF^
 -D wxUSE_TREEBOOK=OFF^
 -D wxUSE_TREECTRL=OFF^
 -D wxUSE_TREELISTCTRL=OFF

set DLG_OPTIONS=-D wxUSE_ABOUTDLG=OFF^
 -D wxUSE_CHOICEDLG=OFF^
 -D wxUSE_COLOURDLG=OFF^
 -D wxUSE_CREDENTIALDLG=OFF^
 -D wxUSE_FINDREPLDLG=OFF^
 -D wxUSE_FONTDLG=OFF^
 -D wxUSE_NUMBERDLG=OFF^
 -D wxUSE_SPLASH=OFF^
 -D wxUSE_TEXTDLG=OFF^
 -D wxUSE_STARTUP_TIPS=OFF^
 -D wxUSE_PROGRESSDLG=OFF^
 -D wxUSE_WIZARDDLG=OFF

set MISC_GUI_OPTIONS=-D wxUSE_MINIFRAME=OFF^
 -D wxUSE_SPLINES=OFF^
 -D wxUSE_MOUSEWHEEL=OFF^
 -D wxUSE_BUSYINFO=OFF^
 -D wxUSE_HOTKEY=OFF^
 -D wxUSE_JOYSTICK=OFF^
 -D wxUSE_METAFILE=OFF^
 -D wxUSE_DRAGIMAGE=OFF^
 -D wxUSE_DC_TRANSFORM_MATRIX=OFF^
 -D wxUSE_WEBVIEW_WEBKIT=OFF^
 -D wxUSE_PRIVATE_FONTS=OFF

REM You can remove a test tool from the release build with "build_wxWidgets.bat NoTest"
if /I "%~1"=="NoTest" (
    set MISC_GUI_OPTIONS=%MISC_GUI_OPTIONS% -D wxUSE_UIACTIONSIMULATOR=OFF
)

set IMG_OPTIONS=-D wxUSE_PALETTE=OFF^
 -D wxUSE_IMAGE=OFF^
 -D wxUSE_GIF=OFF^
 -D wxUSE_PCX=OFF^
 -D wxUSE_TGA=OFF^
 -D wxUSE_IFF=OFF^
 -D wxUSE_PNM=OFF^
 -D wxUSE_XPM=OFF^
 -D wxUSE_ICO_CUR=OFF

set MSW_OPTIONS=-D wxUSE_ACCESSIBILITY=OFF^
 -D wxUSE_ACTIVEX=OFF^
 -D wxUSE_CRASHREPORT=OFF^
 -D wxUSE_DC_CACHEING=OFF^
 -D wxUSE_NATIVE_PROGRESSDLG=OFF^
 -D wxUSE_NATIVE_STATUSBAR=OFF^
 -D wxUSE_OWNER_DRAWN=OFF^
 -D wxUSE_POSTSCRIPT_ARCHITECTURE_IN_MSW=OFF^
 -D wxUSE_TASKBARICON_BALLOONS=OFF^
 -D wxUSE_WEBVIEW_EDGE=OFF^
 -D wxUSE_WEBVIEW_IE=OFF^
 -D wxUSE_WINRT=OFF^
 -D wxUSE_AUTOID_MANAGEMENT=OFF

set wxOPTIONS=-D wxBUILD_COMPATIBILITY=3.1^
 -D wxBUILD_SHARED=OFF^
 -D wxUSE_NO_RTTI=ON^
 -D wxUSE_UNSAFE_WXSTRING_CONV=OFF^
 %LIB_OPTIONS%^
 %NON_GUI_OPTIONS%^
 %BIG_GUI_OPTIONS%^
 %CTRL_OPTIONS%^
 %DLG_OPTIONS%^
 %MISC_GUI_OPTIONS%^
 %IMG_OPTIONS%^
 %MSW_OPTIONS%

@pushd %USERPROFILE%\wxWidgets-%WX_VERSION%
    mkdir %BUILD_TYPE%
    cd %BUILD_TYPE%
    if "%BUILD_TYPE%"=="Release" (
        set CMAKE_OPTIONS=%CMAKE_OPTIONS% %COMPILER_FLAGS%
        set wxOPTIONS=%wxOPTIONS% -D wxBUILD_USE_STATIC_RUNTIME=ON -D wxBUILD_DEBUG_LEVEL=0  -D wxUSE_DEBUGREPORT=OFF -D wxUSE_LOG=OFF
    )
    echo Cmake options: %CMAKE_OPTIONS%
    echo wxOptions: %wxOPTIONS%
    cmake %CMAKE_OPTIONS% %wxOPTIONS% ../
    if %ERRORLEVEL% neq 0 goto :buildend
    cmake --build . --config %BUILD_TYPE%
    if %ERRORLEVEL% neq 0 goto :buildend
    cmake --install . --config %BUILD_TYPE%
    :buildend
@popd

pause
